'use client';

import { useState } from 'react';
import { useRouter, useSearchParams } from 'next/navigation';

export default function StudentJoinPage() { const params = useSearchParams(); const router = useRouter(); const [pin, setPin] = useState(params.get('pin') ?? ''); const [name, setName] = useState(''); const [teamName, setTeamName] = useState(''); const [color, setColor] = useState(''); const [error, setError] = useState(''); const [loading, setLoading] = useState(false);
  const submit = async (event: React.FormEvent) => { event.preventDefault(); setLoading(true); setError(''); const response = await fetch('/api/games/join', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ pin, displayName: name, teamName, color }) }); const data = await response.json(); if (!response.ok) setError(data.error); else { localStorage.setItem(`player_${data.game.id}`, data.player.id); router.push(`/student/game/${data.game.id}`); } setLoading(false); };
  return <main className="mx-auto flex min-h-screen max-w-lg items-center px-6 py-10"><form onSubmit={submit} className="w-full rounded-3xl border border-slate-700 bg-slate-900 p-7 shadow-2xl"><p className="text-sm font-bold uppercase tracking-widest text-cyan-400">Join battle</p><h1 className="mt-2 text-3xl font-black">Choose your team</h1><p className="mt-2 text-slate-400">Team color and team name are required.</p>{error && <p className="mt-5 rounded-xl bg-red-500/20 p-3 text-red-200">{error}</p>}<label className="mt-6 block text-sm font-bold">Game PIN<input required pattern="[0-9]{6}" value={pin} onChange={e => setPin(e.target.value.replace(/\D/g, '').slice(0, 6))} className="mt-2 w-full rounded-xl border border-slate-600 bg-slate-800 p-3 tracking-widest" /></label><label className="mt-4 block text-sm font-bold">Your name<input required maxLength={40} value={name} onChange={e => setName(e.target.value)} className="mt-2 w-full rounded-xl border border-slate-600 bg-slate-800 p-3" /></label><label className="mt-4 block text-sm font-bold">Team name<input required maxLength={40} value={teamName} onChange={e => setTeamName(e.target.value)} className="mt-2 w-full rounded-xl border border-slate-600 bg-slate-800 p-3" /></label><fieldset className="mt-5"><legend className="text-sm font-bold">Team color <span className="text-red-400">*</span></legend><div className="mt-2 grid grid-cols-2 gap-3">{['RED', 'BLUE', 'GREEN', 'YELLOW'].map(option => <label key={option} className={`cursor-pointer rounded-xl border-2 p-3 text-center font-black ${color === option ? 'border-white ring-2 ring-cyan-400' : 'border-slate-600'} ${option === 'RED' ? 'bg-red-500' : option === 'BLUE' ? 'bg-blue-500' : option === 'GREEN' ? 'bg-emerald-500' : 'bg-yellow-400 text-slate-900'}`}><input type="radio" name="color" value={option} checked={color === option} onChange={e => setColor(e.target.value)} className="sr-only" />{option}</label>)}</div></fieldset><button disabled={loading} className="mt-7 w-full rounded-xl bg-cyan-400 px-4 py-3 font-black text-slate-950 disabled:opacity-50">{loading ? 'Joining…' : 'Join battle'}</button></form></main>;
}
